/**
 * Created by erichua on 13/12/2017.
 */
// data generated by http://www.richyli.com/name/index.asp
export default [
  {'searchStr': 'Thị xã Tây Ninh'},
  {'searchStr': 'Huyện Tân Biên'},
  {'searchStr': 'Huyện Tân Châu'},
  {'searchStr': 'Huyện Dương Minh Châu'},
  {'searchStr': 'Huyện Châu Thành'},
  {'searchStr': 'Huyện Hoà Thành'},
  {'searchStr': 'Huyện Bến Cầu'},
  {'searchStr': 'Huyện Gò Dầu'},
  {'searchStr': 'Huyện Trảng Bàng'}
  ]
